// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// DeletePhoto implements deletePhoto operation.
//
// Delete a photo from the server.
//
// DELETE /v1/photos/{id}
func (UnimplementedHandler) DeletePhoto(ctx context.Context, params DeletePhotoParams) (r DeletePhotoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPhoto implements getPhoto operation.
//
// Get a photo from the server by ID.
//
// GET /v1/photos/{id}
func (UnimplementedHandler) GetPhoto(ctx context.Context, params GetPhotoParams) (r GetPhotoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPhotos implements getPhotos operation.
//
// Get photos from the server with pagination.
//
// GET /v1/photos
func (UnimplementedHandler) GetPhotos(ctx context.Context, params GetPhotosParams) (r GetPhotosRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostPhoto implements postPhoto operation.
//
// Upload a new photo to the server.
//
// POST /v1/photos
func (UnimplementedHandler) PostPhoto(ctx context.Context, req *PostPhotoReq) (r PostPhotoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
