// Code generated by ogen, DO NOT EDIT.
package api

type DeletePhotoRes interface {
	deletePhotoRes()
}

type GetPhotoRes interface {
	getPhotoRes()
}

type GetPhotosRes interface {
	getPhotosRes()
}

type PostPhotoRes interface {
	postPhotoRes()
}
